import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import {ToastContainer} from "react-toastify";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio Website - Rahul Dey',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-[url('/assets/PortfolioBG.png')]">
          <NavBar />
            <div className='w-full'>
              {children}
            </div>
          <Footer />
        </main>
        <ToastContainer autoClose={4000} position="top-right"
        hideProgressBar = {false} closeOnClick = {true}
        pauseOnHover = {true} draggable = {true} theme = "colored"/> 
      </body>
    </html>
  )
}
